Fixing regression from rfc0246.
Errors like:

    error: static variables cannot be referenced in a pattern, use a `const` instead

Were all over the place after that rfc was in place.